# 예외처리
  * 예외처리는 프로그램 실행 중에 발생할 수 있는 오류나 예외 상황을 처리하는 방법이다.

```C#
예외 처리 1
using System;

namespace Exception
{
    partial class SampleException 
    {
        int num = 0;
        bool isFinished = false;

        public void TestTryCatch()
        {
            while (!isFinished) { 
                Console.Write("정수를 입력하세요: ");
                string readStr = Console.ReadLine(); 
                
                try
                {
                    num = int.Parse(readStr);
                    isFinished = true; 
                }
                catch(FormatException e)
                {
                    Console.WriteLine(e.Message);
                }
            }

            Console.WriteLine("입력 num: " + num);
        }


    }
}
```
  * try문 안에 입력 받기가 실행이 된다. 정수를 입력했을 경우
  * isFinished가 ture가 되어 조건문은 종료가 되고 맨 마지막
  * **Console.WriteLine("입력 num: " + num)** 코드가 실행되어 프로그램이 종료된다
  * **But** 정수가 아닌 다른 타입을 입력했을 경우 try에서 생긴 오류 부분을
  * catch 구문으로 넘어가 오류메세지를 출력한다.
  * 참고로 **FormatException** C#에서 문자열을 특정 형식으로 변환하는 동안 발생하는 예외이다.
  * 주로 문자열을 숫자나 날짜 등의 다른 데이터 형식으로 변환할 때, 문자열이 기대한 형식과 일치하지 않으면 예외가 발생한다.


```C#
예외 처리2

using System;

namespace Exception
{
    partial class SampleException 
    {
        public void TestException()
        {
            byte maxNum = 10;

            try
            {
                checked
                {
                    maxNum += byte.MaxValue;
                }
            }
            catch (OverflowException e)
            {
                Console.WriteLine(e.Message);
            }
            Console.WriteLine($"maxNum: {maxNum}");
        }
    }
 
}
```
  * try 문 안에 checked를 활용해서 오버플로우가 탐지되었을 경우 바로 catch문으로 가서 오버플로우에 관한 오류 메세지를 출력한다.
  * 참고로 checked는 try catch문 없이도 사용할 수 있는데 예를 들어

 ```C#
try catch문 없는 checked

 byte bNum = byte.MaxValue;
 checked
 {
 bNum += 1;
 }

 Console.WriteLine($"bNum: {bNum}");
```
  * 이런 식으로 사용할 수 있는데 이런 식으로 사용하면
  * try catch문 없이 checked만 사용할 경우 똑같이 오버플로우는 탐지를 하지만 try catch문은 다음 코드로 넘어가고 checked는 바로 프로그램이 종료된다.

```C#
예외처리 3

using System;

namespace Exception
{
    partial class SampleException
    {
        public void ThrowMethod(int num)
        {
            if (num >= 0)   
            {
                Console.WriteLine($"num: {num}");
            }

            else
            {
                throw new  ArgumentException("입력값이 0보다 작아요..");
                // ArgumentException 이게 뭔지 알기
                // 같은 함수 내가 아니라 다른 함수로 던져 버리기
            }
        }

        public void TestThrow()
        {
            try
            {
                ThrowMethod(10);
                ThrowMethod(-10);
            }
            
            catch(ArgumentException e)
            {
                Console.WriteLine(e.Message);
            }

            int? nullNum = null;

            try
            {
                int num = nullNum ?? throw new ArgumentNullException();
            }

            catch (ArgumentNullException e)
            {
                Console.WriteLine(e.Message);
            }

            if (nullNum != null) Console.WriteLine($"nullNum: {nullNum}");

            int? num2 = null;

            try
            {
                num2 = (nullNum != null) ? nullNum : throw new ArgumentNullException();
                // 삼항 연산자를 이렇게 사용할 수 있구나
            } catch(ArgumentNullException e)
            {
                Console.WriteLine(e.Message);
            }
            if (num2 != null) Console.WriteLine($"num2: {num2}");

        }
    }
}
```
  * throw
    * 예외를 명시적으로 발생시킬 때 사용한다.
    * 이는 일반적으로 프로그램의 실행 중에 예기치 않은 상황이 발생했을 때 해당 상황을 호출자에게 알리고 처리할 수 있도록 하는 메커니즘
  * throw 단순 예외
    * **throw new Exception("예외 발생!")**
  * throw 특정 예외
    * **throw new ArgumentNullException("매개변수가 null입니다.")**
